name: First-Workflow
on: [push]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
          - name: Display some Text
            run: echo "Hello GitHub Actions"
          - name: Command in Multiline
            run: 
              node -v
              npm -v