name: Third-Workflow
on: [push]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
          - name: Display files
            run: ls -a
          - uses: actions/checkout@v4
          - name: Display files
            run: ls -a  